/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentTutorRouteImport } from './routes/student.tutor'
import { Route as StudentSolverRouteImport } from './routes/student.solver'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentLessonRouteImport } from './routes/student.lesson'
import { Route as StudentHomeRouteImport } from './routes/student.home'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTutorRoute = StudentTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSolverRoute = StudentSolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonRoute = StudentLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/solver': typeof StudentSolverRoute
  '/student/tutor': typeof StudentTutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/solver': typeof StudentSolverRoute
  '/student/tutor': typeof StudentTutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/parent': typeof ParentRoute
  '/student': typeof StudentRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/solver': typeof StudentSolverRoute
  '/student/tutor': typeof StudentTutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/parent'
    | '/student'
    | '/student/home'
    | '/student/lesson'
    | '/student/progress'
    | '/student/solver'
    | '/student/tutor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/parent'
    | '/student'
    | '/student/home'
    | '/student/lesson'
    | '/student/progress'
    | '/student/solver'
    | '/student/tutor'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/parent'
    | '/student'
    | '/student/home'
    | '/student/lesson'
    | '/student/progress'
    | '/student/solver'
    | '/student/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ParentRoute: typeof ParentRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/tutor': {
      id: '/student/tutor'
      path: '/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof StudentTutorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/solver': {
      id: '/student/solver'
      path: '/solver'
      fullPath: '/student/solver'
      preLoaderRoute: typeof StudentSolverRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lesson': {
      id: '/student/lesson'
      path: '/lesson'
      fullPath: '/student/lesson'
      preLoaderRoute: typeof StudentLessonRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/home': {
      id: '/student/home'
      path: '/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentHomeRoute: typeof StudentHomeRoute
  StudentLessonRoute: typeof StudentLessonRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentSolverRoute: typeof StudentSolverRoute
  StudentTutorRoute: typeof StudentTutorRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentHomeRoute: StudentHomeRoute,
  StudentLessonRoute: StudentLessonRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentSolverRoute: StudentSolverRoute,
  StudentTutorRoute: StudentTutorRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  ParentRoute: ParentRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
