#!/usr/bin/env bash
# Run `expo prebuild` for the target app and inject the Codemagic release
# signing config into android/app/build.gradle.
# Usage: prebuild-android.sh <app-name>
#   app-name: student | parent | teacher
#
# Expects these env vars from Codemagic's android_signing integration:
#   CM_KEYSTORE_PATH, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD
set -euo pipefail

APP="${1:?app name required (student|parent|teacher)}"
APP_DIR="$CM_BUILD_DIR/apps/$APP"

if [ ! -d "$APP_DIR" ]; then
  echo "Error: $APP_DIR does not exist" >&2
  exit 1
fi

cd "$APP_DIR"

echo "==> Generating native Android project for apps/$APP"
npx --yes expo prebuild --platform android --no-install --clean

GRADLE_FILE="$APP_DIR/android/app/build.gradle"
if [ ! -f "$GRADLE_FILE" ]; then
  echo "Error: $GRADLE_FILE not generated by prebuild" >&2
  exit 1
fi

echo "==> Appending release signingConfig to $GRADLE_FILE"
# Gradle allows multiple `android { ... }` blocks; they're merged. Appending a
# second block is the canonical Codemagic pattern and avoids invasive edits to
# the Expo-generated file.
cat >> "$GRADLE_FILE" <<'GRADLE'

// --- Codemagic release signing (appended by scripts/codemagic/prebuild-android.sh) ---
android {
    signingConfigs {
        release {
            if (System.getenv("CM_KEYSTORE_PATH")) {
                storeFile file(System.getenv("CM_KEYSTORE_PATH"))
                storePassword System.getenv("CM_KEYSTORE_PASSWORD")
                keyAlias System.getenv("CM_KEY_ALIAS")
                keyPassword System.getenv("CM_KEY_PASSWORD")
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
GRADLE

echo "==> Done. Gradle wrapper:"
ls -la "$APP_DIR/android/gradlew"
