/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new student account
         * @description Phase 1 only supports student self-registration. Parent linking happens later
         *     via an invite flow. Under-18 sign-ups require parental consent — the API records
         *     a consent token captured during onboarding.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSession"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSession"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh an access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSession"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curriculum/grades/{grade}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics for a grade */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    grade: components["parameters"]["Grade"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curriculum/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a topic with its lesson content */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    topicId: components["parameters"]["TopicId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Topic"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curriculum/topics/{topicId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List practice questions for a topic */
        get: {
            parameters: {
                query?: {
                    difficulty?: components["schemas"]["Difficulty"];
                };
                header?: never;
                path: {
                    topicId: components["parameters"]["TopicId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Question"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a learner event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProgressEventInput"];
                };
            };
            responses: {
                /** @description Accepted (event is queued) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-topic mastery summary for the current student */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            studentId: string;
                            /** Format: date-time */
                            generatedAt: string;
                            mastery: components["schemas"]["TopicMastery"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message to the AI tutor
         * @description Proxies to `ai-services/tutor`. The response is SymPy-validated before
         *     being returned to the caller. Rate-limited to 20 requests / minute
         *     per student.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TutorMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TutorMessageResponse"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream a tutor reply over Server-Sent Events
         * @description Returns `text/event-stream`. Event types:
         *       - `meta`   `{ conversationId }`            (always first)
         *       - `delta`  `{ text }`                      (zero or more)
         *       - `claim`  `{ raw, stem, answer, ok }`     (zero or more — one
         *                                                 per equation as soon
         *                                                 as the SymPy validator
         *                                                 has scored it)
         *       - `done`   `{ reply, validated, provider, model, extracted_claims,
         *                    verified_claims, input_tokens, output_tokens,
         *                    cached_tokens }`
         *       - `error`  `{ message }`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TutorMessageRequest"];
                };
            };
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": unknown;
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent conversations for the current student */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load a conversation by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curriculum/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a student's answer to a curriculum question */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        questionId: string;
                        answer: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            questionId: string;
                            correct: boolean;
                            /**
                             * @description True iff the SymPy validator was reachable AND the
                             *     answer was symbolically evaluated. False means the
                             *     check fell back to literal string equality.
                             */
                            validated: boolean;
                            expected: string;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve a LaTeX expression directly (no OCR) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        latex: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SolverResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or refresh an Expo push token for the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example ExponentPushToken[xxx-xxx] */
                        token: string;
                        /** @enum {string} */
                        platform: "ios" | "android" | "web";
                        /** @enum {string} */
                        appSlug: "student" | "parent" | "teacher";
                        deviceName?: string;
                    };
                };
            };
            responses: {
                /** @description Registered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a previously registered push token */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve a captured equation
         * @description Multipart upload of a still image of a printed equation. Pipeline:
         *     OCR → LaTeX → SymPy → step-wise solution. Rejects unparseable input.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SolverResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Image could not be parsed as an equation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            /** Format: date-time */
            time: string;
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Grade: "R" | number;
        /** @enum {string} */
        Language: "en" | "af" | "zu" | "st" | "xh";
        /** @enum {string} */
        UserRole: "student" | "parent" | "teacher" | "school_admin" | "tutor" | "internal_admin";
        /** @enum {string} */
        Difficulty: "easy" | "medium" | "hard";
        /** @enum {string} */
        ContentArea: "numbers" | "patterns_functions_algebra" | "space_and_shape" | "measurement" | "data_handling";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            grade: components["schemas"]["Grade"];
            language?: components["schemas"]["Language"];
            /** @description Required for under-18 sign-ups. Issued by the consent flow. */
            parentalConsentToken?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSession: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            language: components["schemas"]["Language"];
            displayName?: string;
            /** @description Present when role=student */
            grade?: components["schemas"]["Grade"];
            schoolId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TopicSummary: {
            /** @example g9.alg.linear-eq */
            topicId: string;
            title: string;
            grade: components["schemas"]["Grade"];
            contentArea: components["schemas"]["ContentArea"];
            capsReference?: string;
            estimatedMinutes: number;
        };
        Topic: components["schemas"]["TopicSummary"] & {
            prerequisites: string[];
            learningOutcomes: string[];
            /** @description Lesson body in CommonMark; math via `$...$` and `$$...$$`. */
            lessonMarkdown: string;
        };
        Question: {
            /** @example g9.alg.linear-eq.q001 */
            id: string;
            topicId: string;
            difficulty: components["schemas"]["Difficulty"];
            stem: string;
            answer: string;
            answerLatex: string;
            solutionSteps: string[];
            commonMistakes?: string[];
            tags: string[];
        };
        /** @enum {string} */
        ProgressEventType: "lesson_started" | "lesson_completed" | "question_attempted" | "question_correct" | "question_incorrect" | "tutor_message_sent" | "solver_scan_performed";
        ProgressEventInput: {
            type: components["schemas"]["ProgressEventType"];
            topicId?: string | null;
            questionId?: string | null;
            meta?: {
                [key: string]: unknown;
            };
        };
        TopicMastery: {
            topicId: string;
            masteryScore: number;
            attempts: number;
            correctCount: number;
            /** Format: date-time */
            lastInteractionAt: string;
        };
        TutorMessageRequest: {
            message: string;
            topicId?: string | null;
            /** @description Omit to start a new conversation. */
            conversationId?: string | null;
        };
        TutorMessageResponse: {
            conversationId: string;
            reply: string;
            /**
             * @description True iff every numeric/algebraic claim in `reply` passed SymPy
             *     validation. False means the response is best-effort prose only.
             */
            validated: boolean;
        };
        SolverResponse: {
            accepted: boolean;
            finalAnswer?: string | null;
            steps: {
                explanation: string;
                math: string;
            }[];
            detectedLatex?: string | null;
            /** @description Which OCR backend produced the LaTeX (mock | mathpix | none). */
            ocrProvider?: string;
            ocrConfidence?: number | null;
            detail?: string;
        };
        ConversationSummary: {
            id: string;
            topicId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            preview: string;
            turnCount: number;
        };
        Conversation: {
            id: string;
            studentId: string;
            topicId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            turns: components["schemas"]["ConversationTurn"][];
        };
        ConversationTurn: {
            /** @enum {string} */
            role: "user" | "maya";
            text: string;
            /** Format: date-time */
            occurredAt: string;
            /**
             * @description True iff Maya's reply was fully SymPy-verified. Only meaningful
             *     when role=maya.
             */
            validated?: boolean | null;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Grade: components["schemas"]["Grade"];
        TopicId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
