/**
 * @gomaths/api-client
 *
 * Typed client for the GoMaths backend, generated from
 * `services/backend-api/openapi.yaml`.
 *
 * Two surfaces:
 *
 *   1. `paths` / `components` types from `./generated.ts` (re-exported
 *      below) — generated by `pnpm --filter @gomaths/api-client generate`.
 *      Pure types; no runtime cost.
 *
 *   2. `createClient(...)` — a thin `openapi-fetch` wrapper that takes
 *      a baseUrl + an auth-token getter and returns a strongly-typed
 *      `client.GET("/api/curriculum/topics/{topicId}", { ... })` etc.
 *      Use this from any app/service that talks to the backend; no
 *      bespoke fetch wrappers per endpoint.
 *
 * Note on streaming: the SSE endpoint (`POST /api/tutor/messages/stream`)
 * returns `text/event-stream`, which doesn't fit openapi-fetch's
 * JSON-shaped expectations. Apps still use a dedicated SSE client
 * (e.g. `react-native-sse`) for that route — see
 * `apps/student/lib/tutor.ts:streamTutorMessage`.
 */

import createFetchClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./generated";

export type * from "./generated";

export interface CreateClientOptions {
  baseUrl: string;
  /** Async getter for the current access token (or null when unauthenticated). */
  getAccessToken?: () => Promise<string | null> | string | null;
  /** Called with each Response so callers can hook 401-then-refresh logic, telemetry, etc. */
  onResponse?: (response: Response) => void | Promise<void>;
  fetch?: typeof fetch;
}

export type GoMathsClient = ReturnType<typeof createFetchClient<paths>>;

/**
 * Build a typed client. Example:
 *
 *   const api = createClient({ baseUrl: "https://api.gomaths.co.za", getAccessToken });
 *   const { data, error } = await api.GET("/api/curriculum/grades/{grade}", {
 *     params: { path: { grade: 9 } },
 *   });
 */
export function createClient(options: CreateClientOptions): GoMathsClient {
  const client = createFetchClient<paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
  });

  const authMiddleware: Middleware = {
    async onRequest({ request }) {
      const token = await options.getAccessToken?.();
      if (token) request.headers.set("authorization", `Bearer ${token}`);
      return request;
    },
    async onResponse({ response }) {
      if (options.onResponse) await options.onResponse(response);
      return response;
    },
  };

  client.use(authMiddleware);
  return client;
}
